version: "3.7"

services:
  getir-database:
    image: postgres:11-alpine
    container_name: getir_database
    restart: on-failure
    environment:
      - POSTGRES_DB=getir_pg
      - POSTGRES_USER=getir-dev
      - POSTGRES_PASSWORD=getir123
    ports:
      - 5438:5432
    volumes:
      - getir-database:/var/lib/postgresql/data
    networks:
      - getir-backend
  getir-redis:
    image: redis:6.2.2
    container_name: getir_redis
    ports:
      - 6379:6379
    networks:
      - getir-backend

  getir-readingisgood:
    image: onursabit03/readingisgood:latest
    container_name: getir_readingisgood
    restart: on-failure
    ports:
      - 8090:8090
    environment:
      - DB_URL=getir_database
      - DB_PORT=5432
      - REDIS_URL=getir_redis
      - REDIS_PORT=6379
    networks:
      - getir-backend
    depends_on:
      - getir-database
      - getir-redis

volumes:
  getir-database:

networks:
  getir-backend:
    name: getir-backend-network