application:
  security:
    hours: 5
    key: ZXR1dC1zZWNyZXQ=ZXR1dC1zZWNyZXQ=ZXR1dC1zZWNyZXQ=ZXR1dC1zZWNyZXQ=ZXR1dC1zZWNyZXQ=
logging:
  level:
    org:
      hibernate: error
server:
  port: 8090
  servlet:
    context-path: /api
spring:
  application:
    name: '@application.name@'
  datasource:
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    platform: postgres
    schema: classpath:/db/initialize/schema-postgres.sql
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/getir_pg?currentSchema=getir_dev
    username: getir-dev
    password: getir123
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    change-log: classpath:db/liquibase/liquibase.change-log.xml
    enabled: true
  main:
    banner-mode: 'off'
  redis:
    port: ${REDIS_PORT}
    host: ${REDIS_URL}
